import React from "react";
import { View, Image, StyleSheet } from "react-native";

// Single source of truth for rendering the Haibo brand mark in React
// Native. Uses the PNG derivative of icon.svg (generated by
// scripts/regenerate-icons.mjs) because react-native-svg does not
// render the logo's radial + linear gradients reliably — the green
// body and blue sash fell back to flat colours and the detailed white
// figure paths dropped out entirely. The PNG is square (1024×1024)
// with the logo centered and transparent padding on the short edge,
// so width and height are always equal.

interface HaiboLogoProps {
  /** Rendered size in dp. The logo is rendered as a square bounding box. */
  size?: number;
  /** Optional style override for the wrapping View. */
  style?: any;
}

export function HaiboLogo({ size = 96, style }: HaiboLogoProps) {
  return (
    <View
      style={[
        styles.wrap,
        { width: size, height: size },
        style,
      ]}
      pointerEvents="none"
    >
      <Image
        source={require("../../assets/images/icon.png")}
        style={{ width: size, height: size }}
        resizeMode="contain"
      />
    </View>
  );
}

const styles = StyleSheet.create({
  wrap: {
    alignItems: "center",
    justifyContent: "center",
  },
});
