import { TaxiRoute, TaxiRank, TaxiStop, CommunityPost } from "./types";

export const MOCK_ROUTES: TaxiRoute[] = [
  {
    id: "1",
    origin: "Soweto (Bara)",
    destination: "Johannesburg CBD",
    fare: 20,
    handSignal: "point-up",
    handSignalDescription: "Point finger up",
    region: "Gauteng",
    estimatedTime: "30-45 min",
    originCoords: { latitude: -26.2637, longitude: 27.9449 },
    destinationCoords: { latitude: -26.2041, longitude: 28.0473 },
    routeCoords: [
      { latitude: -26.2637, longitude: 27.9449 },
      { latitude: -26.2550, longitude: 27.9600 },
      { latitude: -26.2400, longitude: 27.9850 },
      { latitude: -26.2250, longitude: 28.0100 },
      { latitude: -26.2150, longitude: 28.0300 },
      { latitude: -26.2041, longitude: 28.0473 },
    ],
  },
  {
    id: "2",
    origin: "Alexandra",
    destination: "Sandton",
    fare: 15,
    handSignal: "flat-hand",
    handSignalDescription: "Flat hand facing down",
    region: "Gauteng",
    estimatedTime: "20-30 min",
    originCoords: { latitude: -26.1059, longitude: 28.0892 },
    destinationCoords: { latitude: -26.1076, longitude: 28.0567 },
    routeCoords: [
      { latitude: -26.1059, longitude: 28.0892 },
      { latitude: -26.1070, longitude: 28.0800 },
      { latitude: -26.1080, longitude: 28.0700 },
      { latitude: -26.1076, longitude: 28.0567 },
    ],
  },
  {
    id: "3",
    origin: "Pretoria CBD",
    destination: "Hatfield",
    fare: 12,
    handSignal: "two-fingers",
    handSignalDescription: "Two fingers up",
    region: "Gauteng",
    estimatedTime: "15-20 min",
    originCoords: { latitude: -25.7479, longitude: 28.1881 },
    destinationCoords: { latitude: -25.7487, longitude: 28.2295 },
    routeCoords: [
      { latitude: -25.7479, longitude: 28.1881 },
      { latitude: -25.7480, longitude: 28.2000 },
      { latitude: -25.7485, longitude: 28.2150 },
      { latitude: -25.7487, longitude: 28.2295 },
    ],
  },
  {
    id: "4",
    origin: "Johannesburg CBD",
    destination: "Randburg",
    fare: 18,
    handSignal: "sideways-point",
    handSignalDescription: "Point sideways",
    region: "Gauteng",
    estimatedTime: "25-35 min",
    originCoords: { latitude: -26.2041, longitude: 28.0473 },
    destinationCoords: { latitude: -26.0936, longitude: 28.0061 },
    routeCoords: [
      { latitude: -26.2041, longitude: 28.0473 },
      { latitude: -26.1800, longitude: 28.0350 },
      { latitude: -26.1500, longitude: 28.0200 },
      { latitude: -26.1200, longitude: 28.0100 },
      { latitude: -26.0936, longitude: 28.0061 },
    ],
  },
  {
    id: "5",
    origin: "Durban CBD",
    destination: "Umlazi",
    fare: 15,
    handSignal: "fist",
    handSignalDescription: "Closed fist",
    region: "KwaZulu-Natal",
    estimatedTime: "30-40 min",
    originCoords: { latitude: -29.8587, longitude: 31.0218 },
    destinationCoords: { latitude: -29.9669, longitude: 30.8975 },
    routeCoords: [
      { latitude: -29.8587, longitude: 31.0218 },
      { latitude: -29.8900, longitude: 31.0000 },
      { latitude: -29.9200, longitude: 30.9600 },
      { latitude: -29.9500, longitude: 30.9200 },
      { latitude: -29.9669, longitude: 30.8975 },
    ],
  },
  {
    id: "6",
    origin: "Cape Town CBD",
    destination: "Khayelitsha",
    fare: 22,
    handSignal: "wave",
    handSignalDescription: "Wave hand side to side",
    region: "Western Cape",
    estimatedTime: "40-55 min",
    originCoords: { latitude: -33.9249, longitude: 18.4241 },
    destinationCoords: { latitude: -34.0383, longitude: 18.6733 },
    routeCoords: [
      { latitude: -33.9249, longitude: 18.4241 },
      { latitude: -33.9500, longitude: 18.4800 },
      { latitude: -33.9800, longitude: 18.5500 },
      { latitude: -34.0100, longitude: 18.6000 },
      { latitude: -34.0383, longitude: 18.6733 },
    ],
  },
  {
    id: "7",
    origin: "Mamelodi",
    destination: "Pretoria CBD",
    fare: 14,
    handSignal: "thumb-up",
    handSignalDescription: "Thumb pointing up",
    region: "Gauteng",
    estimatedTime: "25-35 min",
    originCoords: { latitude: -25.7120, longitude: 28.3520 },
    destinationCoords: { latitude: -25.7479, longitude: 28.1881 },
    routeCoords: [
      { latitude: -25.7120, longitude: 28.3520 },
      { latitude: -25.7200, longitude: 28.3000 },
      { latitude: -25.7300, longitude: 28.2500 },
      { latitude: -25.7400, longitude: 28.2200 },
      { latitude: -25.7479, longitude: 28.1881 },
    ],
  },
  {
    id: "8",
    origin: "Tembisa",
    destination: "Kempton Park",
    fare: 10,
    handSignal: "open-palm",
    handSignalDescription: "Open palm facing forward",
    region: "Gauteng",
    estimatedTime: "15-25 min",
    originCoords: { latitude: -25.9985, longitude: 28.2268 },
    destinationCoords: { latitude: -26.1036, longitude: 28.2338 },
    routeCoords: [
      { latitude: -25.9985, longitude: 28.2268 },
      { latitude: -26.0300, longitude: 28.2280 },
      { latitude: -26.0600, longitude: 28.2300 },
      { latitude: -26.1036, longitude: 28.2338 },
    ],
  },
];

export const MOCK_RANKS: TaxiRank[] = [
  {
    id: "1",
    name: "MTN Taxi Rank",
    latitude: -26.2041,
    longitude: 28.0473,
    address: "Gandhi Square, Johannesburg CBD",
    routes: ["1", "4"],
  },
  {
    id: "2",
    name: "Bara Taxi Rank",
    latitude: -26.2637,
    longitude: 27.9449,
    address: "Chris Hani Baragwanath Hospital, Soweto",
    routes: ["1"],
  },
  {
    id: "3",
    name: "Pretoria Station Rank",
    latitude: -25.7479,
    longitude: 28.1881,
    address: "Pretoria Station, Pretoria CBD",
    routes: ["3", "7"],
  },
  {
    id: "4",
    name: "Sandton Taxi Rank",
    latitude: -26.1076,
    longitude: 28.0567,
    address: "Sandton City Mall, Sandton",
    routes: ["2"],
  },
  {
    id: "5",
    name: "Durban Station Rank",
    latitude: -29.8587,
    longitude: 31.0218,
    address: "Durban Station, Durban CBD",
    routes: ["5"],
  },
];

export const MOCK_STOPS: TaxiStop[] = [
  {
    id: "1",
    name: "Rissik Street Stop",
    latitude: -26.2051,
    longitude: 28.0453,
    routeIds: ["1", "4"],
  },
  {
    id: "2",
    name: "Diepkloof Square",
    latitude: -26.2521,
    longitude: 27.9312,
    routeIds: ["1"],
  },
  {
    id: "3",
    name: "Alexandra Pan Stop",
    latitude: -26.1059,
    longitude: 28.0892,
    routeIds: ["2"],
  },
];

export const MOCK_COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: "1",
    userId: "user1",
    userName: "Thabo M.",
    userType: "commuter",
    avatarType: 0,
    content: "Just had an amazing experience on the Soweto-CBD route today. The driver was so respectful and drove safely. We need more drivers like him!",
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    likes: 24,
    comments: 5,
    isLiked: false,
  },
  {
    id: "2",
    userId: "user2",
    userName: "Nomvula K.",
    userType: "commuter",
    avatarType: 0,
    content: "Anyone else noticed the new taxi stop near Sandton? Makes my morning commute so much easier. Finally some good news!",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    likes: 42,
    comments: 12,
    isLiked: false,
  },
  {
    id: "3",
    userId: "driver1",
    userName: "Sipho D.",
    userType: "driver",
    avatarType: 1,
    content: "As a driver, I appreciate when passengers are patient during peak hours. Traffic in Joburg is no joke! Let's work together for safer roads.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    likes: 89,
    comments: 23,
    isLiked: false,
  },
  {
    id: "4",
    userId: "user3",
    userName: "Lerato P.",
    userType: "commuter",
    avatarType: 0,
    content: "Remember to always check the taxi number plate before getting in. Stay safe out there, everyone!",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    likes: 156,
    comments: 34,
    isLiked: false,
  },
  {
    id: "5",
    userId: "operator1",
    userName: "Taxi Owners Assoc.",
    userType: "operator",
    avatarType: 2,
    content: "We are committed to improving safety standards across our fleet. Report any issues through the app and we will address them promptly.",
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    likes: 203,
    comments: 45,
    isLiked: false,
  },
];

export const HAND_SIGNAL_ICONS: Record<string, string> = {
  "point-up": "arrow-up",
  "flat-hand": "minus",
  "two-fingers": "chevrons-up",
  "sideways-point": "arrow-right",
  "fist": "circle",
  "wave": "wind",
  "thumb-up": "thumbs-up",
  "open-palm": "square",
};

export const ISSUE_TYPES = [
  { value: "reckless_driving", label: "Reckless Driving" },
  { value: "overcrowding", label: "Overcrowding" },
  { value: "rude_driver", label: "Rude Driver" },
  { value: "vehicle_condition", label: "Poor Vehicle Condition" },
  { value: "overcharging", label: "Overcharging" },
  { value: "harassment", label: "Harassment" },
  { value: "accident", label: "Accident" },
  { value: "theft", label: "Theft" },
  { value: "other", label: "Other" },
];

export const SEVERITY_LEVELS = [
  { value: "low", label: "Low", color: "#4CAF50" },
  { value: "medium", label: "Medium", color: "#FF9800" },
  { value: "high", label: "High", color: "#F44336" },
  { value: "critical", label: "Critical", color: "#9C27B0" },
];

export const REGIONS = ["All Regions", "Gauteng", "KwaZulu-Natal", "Western Cape", "Eastern Cape", "Free State"];
